// ==============================================================
// File generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================


// rows
#define rows_BASEADDR 0x0000
#define rows_HIGHADDR 0x0000

// cols
#define cols_BASEADDR 0x0004
#define cols_HIGHADDR 0x0004
