// ==============================================================
// File generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module sobel_filter_top (
s_axi_CONTROL_BUS_ACLK,
s_axi_CONTROL_BUS_ARESETN,
s_axi_CONTROL_BUS_AWADDR,
s_axi_CONTROL_BUS_AWVALID,
s_axi_CONTROL_BUS_AWREADY,
s_axi_CONTROL_BUS_WDATA,
s_axi_CONTROL_BUS_WSTRB,
s_axi_CONTROL_BUS_WVALID,
s_axi_CONTROL_BUS_WREADY,
s_axi_CONTROL_BUS_BRESP,
s_axi_CONTROL_BUS_BVALID,
s_axi_CONTROL_BUS_BREADY,
s_axi_CONTROL_BUS_ARADDR,
s_axi_CONTROL_BUS_ARVALID,
s_axi_CONTROL_BUS_ARREADY,
s_axi_CONTROL_BUS_RDATA,
s_axi_CONTROL_BUS_RRESP,
s_axi_CONTROL_BUS_RVALID,
s_axi_CONTROL_BUS_RREADY,
INPUT_STREAM_TVALID,
INPUT_STREAM_TREADY,
INPUT_STREAM_TDATA,
INPUT_STREAM_TSTRB,
INPUT_STREAM_TUSER,
INPUT_STREAM_TLAST,
INPUT_STREAM_TDEST,
OUTPUT_STREAM_TVALID,
OUTPUT_STREAM_TREADY,
OUTPUT_STREAM_TDATA,
OUTPUT_STREAM_TSTRB,
OUTPUT_STREAM_TUSER,
OUTPUT_STREAM_TLAST,
OUTPUT_STREAM_TDEST,
s_axi_SOBEL_CONTROL_ACLK,
s_axi_SOBEL_CONTROL_ARESETN,
s_axi_SOBEL_CONTROL_AWADDR,
s_axi_SOBEL_CONTROL_AWVALID,
s_axi_SOBEL_CONTROL_AWREADY,
s_axi_SOBEL_CONTROL_WDATA,
s_axi_SOBEL_CONTROL_WSTRB,
s_axi_SOBEL_CONTROL_WVALID,
s_axi_SOBEL_CONTROL_WREADY,
s_axi_SOBEL_CONTROL_BRESP,
s_axi_SOBEL_CONTROL_BVALID,
s_axi_SOBEL_CONTROL_BREADY,
s_axi_SOBEL_CONTROL_ARADDR,
s_axi_SOBEL_CONTROL_ARVALID,
s_axi_SOBEL_CONTROL_ARREADY,
s_axi_SOBEL_CONTROL_RDATA,
s_axi_SOBEL_CONTROL_RRESP,
s_axi_SOBEL_CONTROL_RVALID,
s_axi_SOBEL_CONTROL_RREADY,
SYS_RESET,
SYS_CLK
);

parameter C_S_AXI_CONTROL_BUS_BASEADDR = 32'h00000000;
parameter C_S_AXI_CONTROL_BUS_HIGHADDR = 32'h0000FFFF;
parameter C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 32;
parameter C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32;
parameter C_S_AXI_SOBEL_CONTROL_BASEADDR = 32'h00000000;
parameter C_S_AXI_SOBEL_CONTROL_HIGHADDR = 32'h0000FFFF;
parameter C_S_AXI_SOBEL_CONTROL_ADDR_WIDTH = 32;
parameter C_S_AXI_SOBEL_CONTROL_DATA_WIDTH = 32;
parameter RESET_ACTIVE_LOW = 1;
input s_axi_CONTROL_BUS_ACLK ;
input s_axi_CONTROL_BUS_ARESETN ;
input [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_AWADDR ;
input s_axi_CONTROL_BUS_AWVALID ;
output s_axi_CONTROL_BUS_AWREADY ;
input [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_WDATA ;
input [C_S_AXI_CONTROL_BUS_DATA_WIDTH/8 - 1:0] s_axi_CONTROL_BUS_WSTRB ;
input s_axi_CONTROL_BUS_WVALID ;
output s_axi_CONTROL_BUS_WREADY ;
output [2 - 1:0] s_axi_CONTROL_BUS_BRESP ;
output s_axi_CONTROL_BUS_BVALID ;
input s_axi_CONTROL_BUS_BREADY ;
input [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_ARADDR ;
input s_axi_CONTROL_BUS_ARVALID ;
output s_axi_CONTROL_BUS_ARREADY ;
output [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_RDATA ;
output [2 - 1:0] s_axi_CONTROL_BUS_RRESP ;
output s_axi_CONTROL_BUS_RVALID ;
input s_axi_CONTROL_BUS_RREADY ;


input INPUT_STREAM_TVALID ;
output INPUT_STREAM_TREADY ;
input [24 - 1:0] INPUT_STREAM_TDATA ;
input [3 - 1:0] INPUT_STREAM_TSTRB ;
input [1 - 1:0] INPUT_STREAM_TUSER ;
input [1 - 1:0] INPUT_STREAM_TLAST ;
input [1 - 1:0] INPUT_STREAM_TDEST ;


output OUTPUT_STREAM_TVALID ;
input OUTPUT_STREAM_TREADY ;
output [24 - 1:0] OUTPUT_STREAM_TDATA ;
output [3 - 1:0] OUTPUT_STREAM_TSTRB ;
output [1 - 1:0] OUTPUT_STREAM_TUSER ;
output [1 - 1:0] OUTPUT_STREAM_TLAST ;
output [1 - 1:0] OUTPUT_STREAM_TDEST ;

input s_axi_SOBEL_CONTROL_ACLK ;
input s_axi_SOBEL_CONTROL_ARESETN ;
input [C_S_AXI_SOBEL_CONTROL_ADDR_WIDTH - 1:0] s_axi_SOBEL_CONTROL_AWADDR ;
input s_axi_SOBEL_CONTROL_AWVALID ;
output s_axi_SOBEL_CONTROL_AWREADY ;
input [C_S_AXI_SOBEL_CONTROL_DATA_WIDTH - 1:0] s_axi_SOBEL_CONTROL_WDATA ;
input [C_S_AXI_SOBEL_CONTROL_DATA_WIDTH/8 - 1:0] s_axi_SOBEL_CONTROL_WSTRB ;
input s_axi_SOBEL_CONTROL_WVALID ;
output s_axi_SOBEL_CONTROL_WREADY ;
output [2 - 1:0] s_axi_SOBEL_CONTROL_BRESP ;
output s_axi_SOBEL_CONTROL_BVALID ;
input s_axi_SOBEL_CONTROL_BREADY ;
input [C_S_AXI_SOBEL_CONTROL_ADDR_WIDTH - 1:0] s_axi_SOBEL_CONTROL_ARADDR ;
input s_axi_SOBEL_CONTROL_ARVALID ;
output s_axi_SOBEL_CONTROL_ARREADY ;
output [C_S_AXI_SOBEL_CONTROL_DATA_WIDTH - 1:0] s_axi_SOBEL_CONTROL_RDATA ;
output [2 - 1:0] s_axi_SOBEL_CONTROL_RRESP ;
output s_axi_SOBEL_CONTROL_RVALID ;
input s_axi_SOBEL_CONTROL_RREADY ;

input SYS_RESET ;

input SYS_CLK ;

wire s_axi_CONTROL_BUS_ACLK;
wire s_axi_CONTROL_BUS_ARESETN;
wire [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_AWADDR;
wire s_axi_CONTROL_BUS_AWVALID;
wire s_axi_CONTROL_BUS_AWREADY;
wire [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_WDATA;
wire [C_S_AXI_CONTROL_BUS_DATA_WIDTH/8 - 1:0] s_axi_CONTROL_BUS_WSTRB;
wire s_axi_CONTROL_BUS_WVALID;
wire s_axi_CONTROL_BUS_WREADY;
wire [2 - 1:0] s_axi_CONTROL_BUS_BRESP;
wire s_axi_CONTROL_BUS_BVALID;
wire s_axi_CONTROL_BUS_BREADY;
wire [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_ARADDR;
wire s_axi_CONTROL_BUS_ARVALID;
wire s_axi_CONTROL_BUS_ARREADY;
wire [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_RDATA;
wire [2 - 1:0] s_axi_CONTROL_BUS_RRESP;
wire s_axi_CONTROL_BUS_RVALID;
wire s_axi_CONTROL_BUS_RREADY;


wire INPUT_STREAM_TVALID;
wire INPUT_STREAM_TREADY;
wire [24 - 1:0] INPUT_STREAM_TDATA;
wire [3 - 1:0] INPUT_STREAM_TSTRB;
wire [1 - 1:0] INPUT_STREAM_TUSER;
wire [1 - 1:0] INPUT_STREAM_TLAST;
wire [1 - 1:0] INPUT_STREAM_TDEST;


wire OUTPUT_STREAM_TVALID;
wire OUTPUT_STREAM_TREADY;
wire [24 - 1:0] OUTPUT_STREAM_TDATA;
wire [3 - 1:0] OUTPUT_STREAM_TSTRB;
wire [1 - 1:0] OUTPUT_STREAM_TUSER;
wire [1 - 1:0] OUTPUT_STREAM_TLAST;
wire [1 - 1:0] OUTPUT_STREAM_TDEST;

wire s_axi_SOBEL_CONTROL_ACLK;
wire s_axi_SOBEL_CONTROL_ARESETN;
wire [C_S_AXI_SOBEL_CONTROL_ADDR_WIDTH - 1:0] s_axi_SOBEL_CONTROL_AWADDR;
wire s_axi_SOBEL_CONTROL_AWVALID;
wire s_axi_SOBEL_CONTROL_AWREADY;
wire [C_S_AXI_SOBEL_CONTROL_DATA_WIDTH - 1:0] s_axi_SOBEL_CONTROL_WDATA;
wire [C_S_AXI_SOBEL_CONTROL_DATA_WIDTH/8 - 1:0] s_axi_SOBEL_CONTROL_WSTRB;
wire s_axi_SOBEL_CONTROL_WVALID;
wire s_axi_SOBEL_CONTROL_WREADY;
wire [2 - 1:0] s_axi_SOBEL_CONTROL_BRESP;
wire s_axi_SOBEL_CONTROL_BVALID;
wire s_axi_SOBEL_CONTROL_BREADY;
wire [C_S_AXI_SOBEL_CONTROL_ADDR_WIDTH - 1:0] s_axi_SOBEL_CONTROL_ARADDR;
wire s_axi_SOBEL_CONTROL_ARVALID;
wire s_axi_SOBEL_CONTROL_ARREADY;
wire [C_S_AXI_SOBEL_CONTROL_DATA_WIDTH - 1:0] s_axi_SOBEL_CONTROL_RDATA;
wire [2 - 1:0] s_axi_SOBEL_CONTROL_RRESP;
wire s_axi_SOBEL_CONTROL_RVALID;
wire s_axi_SOBEL_CONTROL_RREADY;

wire SYS_RESET;


wire [32 - 1:0] sig_sobel_filter_rows;
wire [32 - 1:0] sig_sobel_filter_cols;


wire [24 - 1:0] sig_sobel_filter_inter_pix_data_V_dout;
wire sig_sobel_filter_inter_pix_data_V_empty_n;
wire sig_sobel_filter_inter_pix_data_V_read;
wire [3 - 1:0] sig_sobel_filter_inter_pix_strb_V_dout;
wire sig_sobel_filter_inter_pix_strb_V_empty_n;
wire sig_sobel_filter_inter_pix_strb_V_read;
wire [1 - 1:0] sig_sobel_filter_inter_pix_user_V_dout;
wire sig_sobel_filter_inter_pix_user_V_empty_n;
wire sig_sobel_filter_inter_pix_user_V_read;
wire [1 - 1:0] sig_sobel_filter_inter_pix_last_V_dout;
wire sig_sobel_filter_inter_pix_last_V_empty_n;
wire sig_sobel_filter_inter_pix_last_V_read;
wire [1 - 1:0] sig_sobel_filter_inter_pix_tdest_V_dout;
wire sig_sobel_filter_inter_pix_tdest_V_empty_n;
wire sig_sobel_filter_inter_pix_tdest_V_read;


wire [24 - 1:0] sig_sobel_filter_out_pix_data_V_din;
wire sig_sobel_filter_out_pix_data_V_full_n;
wire sig_sobel_filter_out_pix_data_V_write;
wire [3 - 1:0] sig_sobel_filter_out_pix_strb_V_din;
wire sig_sobel_filter_out_pix_strb_V_full_n;
wire sig_sobel_filter_out_pix_strb_V_write;
wire [1 - 1:0] sig_sobel_filter_out_pix_user_V_din;
wire sig_sobel_filter_out_pix_user_V_full_n;
wire sig_sobel_filter_out_pix_user_V_write;
wire [1 - 1:0] sig_sobel_filter_out_pix_last_V_din;
wire sig_sobel_filter_out_pix_last_V_full_n;
wire sig_sobel_filter_out_pix_last_V_write;
wire [1 - 1:0] sig_sobel_filter_out_pix_tdest_V_din;
wire sig_sobel_filter_out_pix_tdest_V_full_n;
wire sig_sobel_filter_out_pix_tdest_V_write;

wire sig_sobel_filter_ap_start;
wire sig_sobel_filter_ap_done;
wire sig_sobel_filter_ap_idle;

wire sig_sobel_filter_ap_rst;




sobel_filter sobel_filter_U(
    .rows(sig_sobel_filter_rows),
    .cols(sig_sobel_filter_cols),
    .inter_pix_data_V_dout(sig_sobel_filter_inter_pix_data_V_dout),
    .inter_pix_data_V_empty_n(sig_sobel_filter_inter_pix_data_V_empty_n),
    .inter_pix_data_V_read(sig_sobel_filter_inter_pix_data_V_read),
    .inter_pix_strb_V_dout(sig_sobel_filter_inter_pix_strb_V_dout),
    .inter_pix_strb_V_empty_n(sig_sobel_filter_inter_pix_strb_V_empty_n),
    .inter_pix_strb_V_read(sig_sobel_filter_inter_pix_strb_V_read),
    .inter_pix_user_V_dout(sig_sobel_filter_inter_pix_user_V_dout),
    .inter_pix_user_V_empty_n(sig_sobel_filter_inter_pix_user_V_empty_n),
    .inter_pix_user_V_read(sig_sobel_filter_inter_pix_user_V_read),
    .inter_pix_last_V_dout(sig_sobel_filter_inter_pix_last_V_dout),
    .inter_pix_last_V_empty_n(sig_sobel_filter_inter_pix_last_V_empty_n),
    .inter_pix_last_V_read(sig_sobel_filter_inter_pix_last_V_read),
    .inter_pix_tdest_V_dout(sig_sobel_filter_inter_pix_tdest_V_dout),
    .inter_pix_tdest_V_empty_n(sig_sobel_filter_inter_pix_tdest_V_empty_n),
    .inter_pix_tdest_V_read(sig_sobel_filter_inter_pix_tdest_V_read),
    .out_pix_data_V_din(sig_sobel_filter_out_pix_data_V_din),
    .out_pix_data_V_full_n(sig_sobel_filter_out_pix_data_V_full_n),
    .out_pix_data_V_write(sig_sobel_filter_out_pix_data_V_write),
    .out_pix_strb_V_din(sig_sobel_filter_out_pix_strb_V_din),
    .out_pix_strb_V_full_n(sig_sobel_filter_out_pix_strb_V_full_n),
    .out_pix_strb_V_write(sig_sobel_filter_out_pix_strb_V_write),
    .out_pix_user_V_din(sig_sobel_filter_out_pix_user_V_din),
    .out_pix_user_V_full_n(sig_sobel_filter_out_pix_user_V_full_n),
    .out_pix_user_V_write(sig_sobel_filter_out_pix_user_V_write),
    .out_pix_last_V_din(sig_sobel_filter_out_pix_last_V_din),
    .out_pix_last_V_full_n(sig_sobel_filter_out_pix_last_V_full_n),
    .out_pix_last_V_write(sig_sobel_filter_out_pix_last_V_write),
    .out_pix_tdest_V_din(sig_sobel_filter_out_pix_tdest_V_din),
    .out_pix_tdest_V_full_n(sig_sobel_filter_out_pix_tdest_V_full_n),
    .out_pix_tdest_V_write(sig_sobel_filter_out_pix_tdest_V_write),
    .ap_start(sig_sobel_filter_ap_start),
    .ap_done(sig_sobel_filter_ap_done),
    .ap_idle(sig_sobel_filter_ap_idle),
    .ap_rst(sig_sobel_filter_ap_rst),
    .ap_clk(SYS_CLK)
);

CONTROL_BUS_if #(
    .C_BASEADDR(C_S_AXI_CONTROL_BUS_BASEADDR),
    .C_HIGHADDR(C_S_AXI_CONTROL_BUS_HIGHADDR),
    .C_ADDR_WIDTH(C_S_AXI_CONTROL_BUS_ADDR_WIDTH),
    .C_DATA_WIDTH(C_S_AXI_CONTROL_BUS_DATA_WIDTH))
CONTROL_BUS_if_U(
    .DOUT_rows(sig_sobel_filter_rows),
    .DOUT_cols(sig_sobel_filter_cols),
    .ACLK(s_axi_CONTROL_BUS_ACLK),
    .ARESETN(s_axi_CONTROL_BUS_ARESETN),
    .AWADDR(s_axi_CONTROL_BUS_AWADDR),
    .AWVALID(s_axi_CONTROL_BUS_AWVALID),
    .AWREADY(s_axi_CONTROL_BUS_AWREADY),
    .WDATA(s_axi_CONTROL_BUS_WDATA),
    .WSTRB(s_axi_CONTROL_BUS_WSTRB),
    .WVALID(s_axi_CONTROL_BUS_WVALID),
    .WREADY(s_axi_CONTROL_BUS_WREADY),
    .BRESP(s_axi_CONTROL_BUS_BRESP),
    .BVALID(s_axi_CONTROL_BUS_BVALID),
    .BREADY(s_axi_CONTROL_BUS_BREADY),
    .ARADDR(s_axi_CONTROL_BUS_ARADDR),
    .ARVALID(s_axi_CONTROL_BUS_ARVALID),
    .ARREADY(s_axi_CONTROL_BUS_ARREADY),
    .RDATA(s_axi_CONTROL_BUS_RDATA),
    .RRESP(s_axi_CONTROL_BUS_RRESP),
    .RVALID(s_axi_CONTROL_BUS_RVALID),
    .RREADY(s_axi_CONTROL_BUS_RREADY));

INPUT_STREAM_if INPUT_STREAM_if_U(
    .clk(SYS_CLK),
    .reset(sig_sobel_filter_ap_rst),
    .inter_pix_data_V_dout(sig_sobel_filter_inter_pix_data_V_dout),
    .inter_pix_data_V_empty_n(sig_sobel_filter_inter_pix_data_V_empty_n),
    .inter_pix_data_V_read(sig_sobel_filter_inter_pix_data_V_read),
    .inter_pix_strb_V_dout(sig_sobel_filter_inter_pix_strb_V_dout),
    .inter_pix_strb_V_empty_n(sig_sobel_filter_inter_pix_strb_V_empty_n),
    .inter_pix_strb_V_read(sig_sobel_filter_inter_pix_strb_V_read),
    .inter_pix_user_V_dout(sig_sobel_filter_inter_pix_user_V_dout),
    .inter_pix_user_V_empty_n(sig_sobel_filter_inter_pix_user_V_empty_n),
    .inter_pix_user_V_read(sig_sobel_filter_inter_pix_user_V_read),
    .inter_pix_last_V_dout(sig_sobel_filter_inter_pix_last_V_dout),
    .inter_pix_last_V_empty_n(sig_sobel_filter_inter_pix_last_V_empty_n),
    .inter_pix_last_V_read(sig_sobel_filter_inter_pix_last_V_read),
    .inter_pix_tdest_V_dout(sig_sobel_filter_inter_pix_tdest_V_dout),
    .inter_pix_tdest_V_empty_n(sig_sobel_filter_inter_pix_tdest_V_empty_n),
    .inter_pix_tdest_V_read(sig_sobel_filter_inter_pix_tdest_V_read),
    .TVALID(INPUT_STREAM_TVALID),
    .TREADY(INPUT_STREAM_TREADY),
    .TDATA(INPUT_STREAM_TDATA),
    .TSTRB(INPUT_STREAM_TSTRB),
    .TUSER(INPUT_STREAM_TUSER),
    .TLAST(INPUT_STREAM_TLAST),
    .TDEST(INPUT_STREAM_TDEST));

OUTPUT_STREAM_if OUTPUT_STREAM_if_U(
    .clk(SYS_CLK),
    .reset(sig_sobel_filter_ap_rst),
    .out_pix_data_V_din(sig_sobel_filter_out_pix_data_V_din),
    .out_pix_data_V_full_n(sig_sobel_filter_out_pix_data_V_full_n),
    .out_pix_data_V_write(sig_sobel_filter_out_pix_data_V_write),
    .out_pix_strb_V_din(sig_sobel_filter_out_pix_strb_V_din),
    .out_pix_strb_V_full_n(sig_sobel_filter_out_pix_strb_V_full_n),
    .out_pix_strb_V_write(sig_sobel_filter_out_pix_strb_V_write),
    .out_pix_user_V_din(sig_sobel_filter_out_pix_user_V_din),
    .out_pix_user_V_full_n(sig_sobel_filter_out_pix_user_V_full_n),
    .out_pix_user_V_write(sig_sobel_filter_out_pix_user_V_write),
    .out_pix_last_V_din(sig_sobel_filter_out_pix_last_V_din),
    .out_pix_last_V_full_n(sig_sobel_filter_out_pix_last_V_full_n),
    .out_pix_last_V_write(sig_sobel_filter_out_pix_last_V_write),
    .out_pix_tdest_V_din(sig_sobel_filter_out_pix_tdest_V_din),
    .out_pix_tdest_V_full_n(sig_sobel_filter_out_pix_tdest_V_full_n),
    .out_pix_tdest_V_write(sig_sobel_filter_out_pix_tdest_V_write),
    .TVALID(OUTPUT_STREAM_TVALID),
    .TREADY(OUTPUT_STREAM_TREADY),
    .TDATA(OUTPUT_STREAM_TDATA),
    .TSTRB(OUTPUT_STREAM_TSTRB),
    .TUSER(OUTPUT_STREAM_TUSER),
    .TLAST(OUTPUT_STREAM_TLAST),
    .TDEST(OUTPUT_STREAM_TDEST));

SOBEL_CONTROL_if #(
    .C_BASEADDR(C_S_AXI_SOBEL_CONTROL_BASEADDR),
    .C_HIGHADDR(C_S_AXI_SOBEL_CONTROL_HIGHADDR),
    .C_ADDR_WIDTH(C_S_AXI_SOBEL_CONTROL_ADDR_WIDTH),
    .C_DATA_WIDTH(C_S_AXI_SOBEL_CONTROL_DATA_WIDTH))
SOBEL_CONTROL_if_U(
    .DOUT_ap_start(sig_sobel_filter_ap_start),
    .DIN_ap_done(sig_sobel_filter_ap_done),
    .DIN_ap_idle(sig_sobel_filter_ap_idle),
    .ACLK(s_axi_SOBEL_CONTROL_ACLK),
    .ARESETN(s_axi_SOBEL_CONTROL_ARESETN),
    .AWADDR(s_axi_SOBEL_CONTROL_AWADDR),
    .AWVALID(s_axi_SOBEL_CONTROL_AWVALID),
    .AWREADY(s_axi_SOBEL_CONTROL_AWREADY),
    .WDATA(s_axi_SOBEL_CONTROL_WDATA),
    .WSTRB(s_axi_SOBEL_CONTROL_WSTRB),
    .WVALID(s_axi_SOBEL_CONTROL_WVALID),
    .WREADY(s_axi_SOBEL_CONTROL_WREADY),
    .BRESP(s_axi_SOBEL_CONTROL_BRESP),
    .BVALID(s_axi_SOBEL_CONTROL_BVALID),
    .BREADY(s_axi_SOBEL_CONTROL_BREADY),
    .ARADDR(s_axi_SOBEL_CONTROL_ARADDR),
    .ARVALID(s_axi_SOBEL_CONTROL_ARVALID),
    .ARREADY(s_axi_SOBEL_CONTROL_ARREADY),
    .RDATA(s_axi_SOBEL_CONTROL_RDATA),
    .RRESP(s_axi_SOBEL_CONTROL_RRESP),
    .RVALID(s_axi_SOBEL_CONTROL_RVALID),
    .RREADY(s_axi_SOBEL_CONTROL_RREADY));

sobel_filter_ap_rst_if #(
    .RESET_ACTIVE_LOW(RESET_ACTIVE_LOW))
ap_rst_if_U(
    .dout(sig_sobel_filter_ap_rst),
    .din(SYS_RESET));

endmodule
