// ==============================================================
// RTL generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2012.1
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sobel_filter (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        inter_pix_data_V_dout,
        inter_pix_data_V_empty_n,
        inter_pix_data_V_read,
        inter_pix_strb_V_dout,
        inter_pix_strb_V_empty_n,
        inter_pix_strb_V_read,
        inter_pix_user_V_dout,
        inter_pix_user_V_empty_n,
        inter_pix_user_V_read,
        inter_pix_last_V_dout,
        inter_pix_last_V_empty_n,
        inter_pix_last_V_read,
        inter_pix_tdest_V_dout,
        inter_pix_tdest_V_empty_n,
        inter_pix_tdest_V_read,
        out_pix_data_V_din,
        out_pix_data_V_full_n,
        out_pix_data_V_write,
        out_pix_strb_V_din,
        out_pix_strb_V_full_n,
        out_pix_strb_V_write,
        out_pix_user_V_din,
        out_pix_user_V_full_n,
        out_pix_user_V_write,
        out_pix_last_V_din,
        out_pix_last_V_full_n,
        out_pix_last_V_write,
        out_pix_tdest_V_din,
        out_pix_tdest_V_full_n,
        out_pix_tdest_V_write,
        rows,
        cols
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
input  [23:0] inter_pix_data_V_dout;
input   inter_pix_data_V_empty_n;
output   inter_pix_data_V_read;
input  [2:0] inter_pix_strb_V_dout;
input   inter_pix_strb_V_empty_n;
output   inter_pix_strb_V_read;
input  [0:0] inter_pix_user_V_dout;
input   inter_pix_user_V_empty_n;
output   inter_pix_user_V_read;
input  [0:0] inter_pix_last_V_dout;
input   inter_pix_last_V_empty_n;
output   inter_pix_last_V_read;
input  [0:0] inter_pix_tdest_V_dout;
input   inter_pix_tdest_V_empty_n;
output   inter_pix_tdest_V_read;
output  [23:0] out_pix_data_V_din;
input   out_pix_data_V_full_n;
output   out_pix_data_V_write;
output  [2:0] out_pix_strb_V_din;
input   out_pix_strb_V_full_n;
output   out_pix_strb_V_write;
output  [0:0] out_pix_user_V_din;
input   out_pix_user_V_full_n;
output   out_pix_user_V_write;
output  [0:0] out_pix_last_V_din;
input   out_pix_last_V_full_n;
output   out_pix_last_V_write;
output  [0:0] out_pix_tdest_V_din;
input   out_pix_tdest_V_full_n;
output   out_pix_tdest_V_write;
input  [31:0] rows;
input  [31:0] cols;

reg ap_done;
reg ap_idle;
reg inter_pix_data_V_read;
reg inter_pix_strb_V_read;
reg inter_pix_user_V_read;
reg inter_pix_last_V_read;
reg inter_pix_tdest_V_read;
reg out_pix_data_V_write;
reg out_pix_strb_V_write;
reg out_pix_user_V_write;
reg out_pix_last_V_write;
reg out_pix_tdest_V_write;
reg   [1:0] ap_CS_fsm = 2'b00;
reg   [30:0] col_1_reg_357;
reg   [30:0] ap_reg_ppstg_col_1_reg_357_pp0_it1;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg   [0:0] exitcond_reg_1318;
reg   [0:0] tmp_17_reg_1346;
reg    ap_sig_bdd_85;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1318_pp0_it6;
reg   [0:0] or_cond2_reg_1357;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1357_pp0_it6;
reg    ap_sig_bdd_120;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg   [30:0] ap_reg_ppstg_col_1_reg_357_pp0_it2;
reg   [30:0] ap_reg_ppstg_col_1_reg_357_pp0_it3;
reg   [31:0] tmp_s_reg_1270;
reg   [31:0] tmp_7_reg_1275;
reg   [30:0] smax3_reg_1280;
reg   [30:0] smax6_reg_1285;
reg   [30:0] row_1_reg_1293;
reg   [0:0] tmp_8_reg_1298;
wire   [0:0] exitcond3_fu_434_p2;
reg   [0:0] icmp_reg_1303;
reg   [0:0] tmp_11_reg_1308;
reg   [0:0] tmp_13_reg_1313;
wire   [0:0] exitcond_fu_481_p2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1318_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1318_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1318_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1318_pp0_it4;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1318_pp0_it5;
reg   [30:0] col_reg_1322;
wire   [0:0] tmp_15_fu_492_p2;
reg   [0:0] tmp_15_reg_1327;
reg   [0:0] ap_reg_ppstg_tmp_15_reg_1327_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_15_reg_1327_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_15_reg_1327_pp0_it3;
wire   [63:0] tmp_16_fu_497_p1;
reg   [63:0] tmp_16_reg_1334;
reg   [10:0] buff_A_M_1_addr_reg_1340;
reg   [10:0] ap_reg_ppstg_buff_A_M_1_addr_reg_1340_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_17_reg_1346_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_17_reg_1346_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_17_reg_1346_pp0_it3;
reg   [0:0] or_cond1_reg_1350;
reg   [0:0] ap_reg_ppstg_or_cond1_reg_1350_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond1_reg_1350_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond1_reg_1350_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond1_reg_1350_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond1_reg_1350_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond1_reg_1350_pp0_it6;
wire   [0:0] or_cond2_fu_550_p2;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1357_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1357_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1357_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1357_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1357_pp0_it5;
reg   [0:0] output_pixel_last_V_reg_1361;
reg   [0:0] ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it1;
reg   [0:0] ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it2;
reg   [0:0] ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it3;
reg   [0:0] ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it4;
reg   [0:0] ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it5;
reg   [0:0] ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it6;
reg   [7:0] new_pix_R_V_reg_1371;
reg   [7:0] ap_reg_ppstg_new_pix_R_V_reg_1371_pp0_it2;
reg   [7:0] new_pix_G_V_reg_1378;
reg   [7:0] ap_reg_ppstg_new_pix_G_V_reg_1378_pp0_it2;
reg   [7:0] new_pix_B_V_reg_1385;
reg   [12:0] tmp_3_i_reg_1390;
reg   [12:0] tmp_3_i1_reg_1400;
reg   [7:0] buff_C_M_0_1_2_reg_1405;
reg   [7:0] buff_C_M_1_1_1_reg_1410;
reg   [7:0] tmp_26_reg_1415;
reg   [7:0] tmp_27_reg_1420;
reg   [7:0] buff_C_M_1_2_3_reg_1425;
reg   [8:0] x_weight_reg_1430;
reg   [8:0] tmp10_reg_1435;
reg   [7:0] buff_C_M_2_2_3_reg_1440;
reg   [10:0] x_weight_3_reg_1445;
reg   [10:0] y_weight_2_reg_1450;
reg   [7:0] abs_i_reg_1455;
reg   [7:0] abs9_i_reg_1460;
wire   [7:0] tmp_i2_fu_1104_p2;
reg   [7:0] tmp_i2_reg_1465;
wire   [0:0] tmp_8_i_fu_1108_p2;
reg   [0:0] tmp_8_i_reg_1470;
reg   [0:0] tmp_i_s_reg_1475;
reg   [0:0] sel_tmp_reg_1480;
wire   [10:0] buff_A_M_0_address0;
reg    buff_A_M_0_ce0;
wire   [7:0] buff_A_M_0_q0;
wire   [10:0] buff_A_M_0_address1;
reg    buff_A_M_0_ce1;
reg    buff_A_M_0_we1;
wire   [7:0] buff_A_M_0_d1;
wire   [10:0] buff_A_M_1_address0;
reg    buff_A_M_1_ce0;
wire   [7:0] buff_A_M_1_q0;
wire   [10:0] buff_A_M_1_address1;
reg    buff_A_M_1_ce1;
reg    buff_A_M_1_we1;
wire   [7:0] buff_A_M_1_d1;
wire   [10:0] buff_A_M_2_address0;
reg    buff_A_M_2_ce0;
reg    buff_A_M_2_we0;
wire   [7:0] buff_A_M_2_d0;
wire   [10:0] buff_A_M_2_address1;
reg    buff_A_M_2_ce1;
wire   [7:0] buff_A_M_2_q1;
reg   [30:0] row_reg_346;
reg   [30:0] col_1_phi_fu_361_p4;
wire   [63:0] tmp_19_fu_620_p1;
wire   [63:0] tmp_18_fu_886_p1;
reg   [7:0] temp_fu_156;
reg   [7:0] tempx_R_V_fu_160;
reg   [7:0] tempx_B_V_fu_164;
reg   [7:0] tempx_G_V_fu_168;
reg   [7:0] buff_C_M_2_2_fu_172;
reg   [7:0] buff_C_M_0_1_fu_176;
reg   [7:0] buff_C_M_0_2_fu_180;
wire   [7:0] buff_C_M_0_2_4_fu_836_p3;
reg   [7:0] buff_C_M_2_1_fu_184;
reg   [7:0] buff_C_M_1_1_fu_188;
reg   [7:0] buff_C_M_1_2_fu_192;
wire   [31:0] tmp_fu_382_p2;
wire   [31:0] tmp1_fu_392_p2;
wire   [0:0] tmp2_fu_402_p2;
wire   [30:0] tmp_cast_fu_388_p1;
wire   [0:0] tmp5_fu_416_p2;
wire   [30:0] tmp1_cast_fu_398_p1;
wire   [31:0] row_cast_fu_430_p1;
wire   [29:0] tmp_24_fu_450_p4;
wire   [31:0] col_assign_cast_fu_477_p1;
wire   [29:0] tmp_28_fu_507_p4;
wire   [0:0] icmp7_fu_517_p2;
wire   [0:0] tmp_20_fu_523_p2;
wire   [0:0] tmp9_fu_533_p2;
wire   [0:0] tmp8_fu_528_p2;
wire   [0:0] tmp_22_fu_544_p2;
wire   [7:0] tmp_2_i_fu_597_p0;
wire   [12:0] tmp_2_i_fu_597_p2;
wire   [7:0] tmp_2_i1_fu_629_p0;
wire   [12:0] tmp_2_i1_fu_629_p2;
wire   [13:0] retval_i_i_cast_fu_650_p1;
wire   [13:0] p_shl_i_fu_653_p2;
wire   [8:0] retval_i_i_cast1_fu_647_p1;
wire   [8:0] p_shl1_i_fu_663_p2;
wire   [14:0] p_shl_i_cast_fu_659_p1;
wire   [14:0] p_shl1_i_cast_fu_669_p1;
wire   [14:0] tmp_i_fu_673_p2;
wire   [14:0] retval_i7_i_cast_fu_686_p1;
wire   [14:0] p_shl2_i_fu_689_p2;
wire   [15:0] p_shl2_i_cast_fu_695_p1;
wire   [15:0] tmp_i_cast_fu_679_p1;
wire   [12:0] retval_i7_i_cast1_cast_fu_683_p1;
wire   [12:0] tmp4_fu_705_p2;
wire   [15:0] tmp4_cast_fu_710_p1;
wire   [15:0] tmp3_fu_699_p2;
wire   [15:0] tmp_5_i_fu_714_p2;
wire   [13:0] retval_i_i1_cast_fu_746_p1;
wire   [13:0] p_shl_i1_fu_750_p2;
wire   [8:0] retval_i_i1_cast1_fu_742_p1;
wire   [8:0] p_shl1_i1_fu_760_p2;
wire   [14:0] p_shl_i1_cast_fu_756_p1;
wire   [14:0] p_shl1_i1_cast_fu_766_p1;
wire   [14:0] tmp_i1_fu_770_p2;
wire   [14:0] retval_i7_i1_cast_fu_784_p1;
wire   [14:0] p_shl2_i1_fu_788_p2;
wire   [15:0] p_shl2_i1_cast_fu_794_p1;
wire   [15:0] tmp_i1_cast_fu_776_p1;
wire   [12:0] retval_i7_i1_cast9_cast_fu_780_p1;
wire   [12:0] tmp7_fu_804_p2;
wire   [15:0] tmp7_cast_fu_809_p1;
wire   [15:0] tmp6_fu_798_p2;
wire   [15:0] tmp_5_i1_fu_813_p2;
wire   [8:0] tmp_2_0_2_i_cast_fu_855_p1;
wire   [8:0] y_weight_cast8_fu_843_p1;
wire   [8:0] y_weight_cast_cast_fu_847_p1;
wire   [8:0] tmp_2_0_2_i_cast7_cast_fu_851_p1;
wire   [7:0] y_2_fu_906_p2;
wire   [8:0] tmp_2_0_1_i_cast_fu_918_p1;
wire   [8:0] tmp_6_0_1_i_fu_921_p2;
wire   [9:0] tmp10_cast_fu_934_p1;
wire   [9:0] tmp_6_0_1_i_cast_fu_927_p1;
wire   [9:0] y_weight_fu_937_p2;
wire   [8:0] tmp_2_1_0_i_cast_fu_947_p1;
wire   [8:0] p_shl_i2_fu_951_p2;
wire   [10:0] x_weight_1_fu_961_p0;
wire   [10:0] p_shl_i2_cast_fu_957_p1;
wire   [8:0] tmp_2_1_2_i_cast_fu_967_p1;
wire   [8:0] tmp_4_1_2_i_fu_970_p2;
wire   [10:0] x_weight_1_fu_961_p2;
wire   [10:0] tmp_4_1_2_i_cast_fu_976_p1;
wire   [10:0] x_weight_2_fu_980_p2;
wire   [10:0] tmp_2_2_0_i_cast_fu_986_p1;
wire   [10:0] y_weight_2_cast_fu_943_p1;
wire   [8:0] tmp_2_2_1_i_cast_fu_1002_p1;
wire   [8:0] p_shl12_i_fu_1006_p2;
wire   [10:0] y_weight_1_fu_996_p2;
wire   [10:0] p_shl12_i_cast_fu_1012_p1;
wire   [10:0] tmp_2_2_2_i_cast_fu_1039_p1;
wire   [10:0] x_weight_4_fu_1042_p2;
wire   [10:0] y_weight_3_fu_1051_p2;
wire   [7:0] x_weight_4_cast_fu_1047_p1;
wire   [0:0] tmp_29_fu_1066_p3;
wire   [7:0] neg_i_cast_fu_1060_p2;
wire   [7:0] y_weight_5_cast_fu_1056_p1;
wire   [0:0] tmp_30_fu_1088_p3;
wire   [7:0] neg7_i_cast_fu_1082_p2;
wire   [0:0] sel_tmp22_demorgan_fu_1120_p2;
wire   [0:0] sel_tmp1_fu_1136_p2;
wire   [0:0] sel_tmp3_fu_1145_p2;
wire   [0:0] sel_tmp4_fu_1150_p2;
wire   [0:0] tmp_21_fu_1140_p2;
wire   [0:0] tmp_23_fu_1159_p2;
wire   [7:0] edge_B_V_fu_1165_p1;
wire   [7:0] edge_val_fu_1131_p2;
wire   [7:0] edge_B_V_fu_1165_p3;
wire   [15:0] p_Result_s_fu_1173_p3;
wire   [23:0] p_Repl2_1_fu_1181_p1;
wire   [31:0] p_Result_1_fu_1185_p3;
reg   [1:0] ap_NS_fsm;
wire   [63:0] buff_A_M_1_addr_reg_13400;
wire   [12:0] tmp_2_i1_fu_629_p00;
wire   [12:0] tmp_2_i_fu_597_p00;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st0_fsm_0 = 2'b00;
parameter    ap_ST_st1_fsm_1 = 2'b01;
parameter    ap_ST_st2_fsm_2 = 2'b10;
parameter    ap_ST_pp0_stg0_fsm_3 = 2'b11;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv31_0 = 31'b0000000000000000000000000000000;
parameter    ap_const_lv32_17 = 32'b00000000000000000000000000010111;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv3_7 = 3'b111;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b00000000000000000000000000000001;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv31_1 = 31'b0000000000000000000000000000001;
parameter    ap_const_lv32_1E = 32'b00000000000000000000000000011110;
parameter    ap_const_lv30_1 = 30'b000000000000000000000000000001;
parameter    ap_const_lv32_8 = 32'b00000000000000000000000000001000;
parameter    ap_const_lv32_F = 32'b00000000000000000000000000001111;
parameter    ap_const_lv32_10 = 32'b00000000000000000000000000010000;
parameter    ap_const_lv13_19 = 13'b0000000011001;
parameter    ap_const_lv13_80 = 13'b0000010000000;
parameter    ap_const_lv14_6 = 14'b00000000000110;
parameter    ap_const_lv9_1 = 9'b000000001;
parameter    ap_const_lv15_7 = 15'b000000000000111;
parameter    ap_const_lv8_10 = 8'b00010000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv32_A = 32'b00000000000000000000000000001010;
parameter    ap_const_lv8_37 = 8'b00110111;
parameter    ap_const_lv8_9B = 8'b10011011;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_true = 1'b1;


sobel_filter_buff_A_M_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buff_A_M_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buff_A_M_0_address0 ),
    .ce0( buff_A_M_0_ce0 ),
    .q0( buff_A_M_0_q0 ),
    .address1( buff_A_M_0_address1 ),
    .ce1( buff_A_M_0_ce1 ),
    .we1( buff_A_M_0_we1 ),
    .d1( buff_A_M_0_d1 )
);

sobel_filter_buff_A_M_1 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buff_A_M_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buff_A_M_1_address0 ),
    .ce0( buff_A_M_1_ce0 ),
    .q0( buff_A_M_1_q0 ),
    .address1( buff_A_M_1_address1 ),
    .ce1( buff_A_M_1_ce1 ),
    .we1( buff_A_M_1_we1 ),
    .d1( buff_A_M_1_d1 )
);

sobel_filter_buff_A_M_2 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buff_A_M_2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buff_A_M_2_address0 ),
    .ce0( buff_A_M_2_ce0 ),
    .we0( buff_A_M_2_we0 ),
    .d0( buff_A_M_2_d0 ),
    .address1( buff_A_M_2_address1 ),
    .ce1( buff_A_M_2_ce1 ),
    .q1( buff_A_M_2_q1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == exitcond_fu_481_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
            ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end else if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2)) | ((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
            ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
            ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
            ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it4))) begin
        if (tmp_30_fu_1088_p3) begin
            abs9_i_reg_1460 <= neg7_i_cast_fu_1082_p2;
        end else begin
            abs9_i_reg_1460 <= y_weight_5_cast_fu_1056_p1;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it4))) begin
        if (tmp_29_fu_1066_p3) begin
            abs_i_reg_1455 <= neg_i_cast_fu_1060_p2;
        end else begin
            abs_i_reg_1455 <= x_weight_4_cast_fu_1047_p1;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_buff_A_M_1_addr_reg_1340_pp0_it1 <= buff_A_M_1_addr_reg_1340;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_col_1_reg_357_pp0_it1 <= col_1_reg_357;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_col_1_reg_357_pp0_it2 <= ap_reg_ppstg_col_1_reg_357_pp0_it1;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_col_1_reg_357_pp0_it3 <= ap_reg_ppstg_col_1_reg_357_pp0_it2;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond_reg_1318_pp0_it1 <= exitcond_reg_1318;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond_reg_1318_pp0_it2 <= ap_reg_ppstg_exitcond_reg_1318_pp0_it1;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond_reg_1318_pp0_it3 <= ap_reg_ppstg_exitcond_reg_1318_pp0_it2;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond_reg_1318_pp0_it4 <= ap_reg_ppstg_exitcond_reg_1318_pp0_it3;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond_reg_1318_pp0_it5 <= ap_reg_ppstg_exitcond_reg_1318_pp0_it4;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond_reg_1318_pp0_it6 <= ap_reg_ppstg_exitcond_reg_1318_pp0_it5;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_new_pix_G_V_reg_1378_pp0_it2 <= new_pix_G_V_reg_1378;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_new_pix_R_V_reg_1371_pp0_it2 <= new_pix_R_V_reg_1371;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond1_reg_1350_pp0_it1 <= or_cond1_reg_1350;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond1_reg_1350_pp0_it2 <= ap_reg_ppstg_or_cond1_reg_1350_pp0_it1;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond1_reg_1350_pp0_it3 <= ap_reg_ppstg_or_cond1_reg_1350_pp0_it2;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond1_reg_1350_pp0_it4 <= ap_reg_ppstg_or_cond1_reg_1350_pp0_it3;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond1_reg_1350_pp0_it5 <= ap_reg_ppstg_or_cond1_reg_1350_pp0_it4;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond1_reg_1350_pp0_it6 <= ap_reg_ppstg_or_cond1_reg_1350_pp0_it5;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond2_reg_1357_pp0_it1 <= or_cond2_reg_1357;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond2_reg_1357_pp0_it2 <= ap_reg_ppstg_or_cond2_reg_1357_pp0_it1;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond2_reg_1357_pp0_it3 <= ap_reg_ppstg_or_cond2_reg_1357_pp0_it2;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond2_reg_1357_pp0_it4 <= ap_reg_ppstg_or_cond2_reg_1357_pp0_it3;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond2_reg_1357_pp0_it5 <= ap_reg_ppstg_or_cond2_reg_1357_pp0_it4;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_or_cond2_reg_1357_pp0_it6 <= ap_reg_ppstg_or_cond2_reg_1357_pp0_it5;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it1 <= output_pixel_last_V_reg_1361;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it2 <= ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it1;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it3 <= ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it2;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it4 <= ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it3;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it5 <= ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it4;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it6 <= ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it5;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_tmp_15_reg_1327_pp0_it1 <= tmp_15_reg_1327;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_tmp_15_reg_1327_pp0_it2 <= ap_reg_ppstg_tmp_15_reg_1327_pp0_it1;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_tmp_15_reg_1327_pp0_it3 <= ap_reg_ppstg_tmp_15_reg_1327_pp0_it2;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_tmp_17_reg_1346_pp0_it1 <= tmp_17_reg_1346;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_tmp_17_reg_1346_pp0_it2 <= ap_reg_ppstg_tmp_17_reg_1346_pp0_it1;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_tmp_17_reg_1346_pp0_it3 <= ap_reg_ppstg_tmp_17_reg_1346_pp0_it2;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == exitcond_fu_481_p2) & ~(ap_const_lv1_0 == tmp_15_fu_492_p2))) begin
        buff_A_M_1_addr_reg_1340 <= buff_A_M_1_addr_reg_13400;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        buff_C_M_0_1_2_reg_1405 <= buff_C_M_0_2_fu_180;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it2))) begin
        buff_C_M_0_1_fu_176 <= buff_C_M_0_2_fu_180;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it2))) begin
        if (ap_reg_ppstg_tmp_15_reg_1327_pp0_it2) begin
            buff_C_M_0_2_fu_180 <= buff_A_M_2_q1;
        end else begin
            buff_C_M_0_2_fu_180 <= buff_C_M_0_2_fu_180;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        buff_C_M_1_1_1_reg_1410 <= buff_C_M_1_2_fu_192;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it3))) begin
        buff_C_M_1_1_fu_188 <= buff_C_M_1_1_1_reg_1410;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it2))) begin
        if (ap_reg_ppstg_tmp_15_reg_1327_pp0_it2) begin
            buff_C_M_1_2_3_reg_1425 <= temp_fu_156;
        end else begin
            buff_C_M_1_2_3_reg_1425 <= buff_C_M_1_2_fu_192;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it2))) begin
        if (ap_reg_ppstg_tmp_15_reg_1327_pp0_it2) begin
            buff_C_M_1_2_fu_192 <= temp_fu_156;
        end else begin
            buff_C_M_1_2_fu_192 <= buff_C_M_1_2_fu_192;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it3))) begin
        buff_C_M_2_1_fu_184 <= buff_C_M_2_2_fu_172;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it3))) begin
        if (ap_reg_ppstg_tmp_15_reg_1327_pp0_it3) begin
            buff_C_M_2_2_3_reg_1440 <= y_2_fu_906_p2;
        end else begin
            buff_C_M_2_2_3_reg_1440 <= buff_C_M_2_2_fu_172;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it3))) begin
        if (ap_reg_ppstg_tmp_15_reg_1327_pp0_it3) begin
            buff_C_M_2_2_fu_172 <= y_2_fu_906_p2;
        end else begin
            buff_C_M_2_2_fu_172 <= buff_C_M_2_2_fu_172;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        col_1_reg_357 <= col_reg_1322;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
        col_1_reg_357 <= ap_const_lv31_0;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        col_reg_1322 <= (col_1_phi_fu_361_p4 + ap_const_lv31_1);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        exitcond_reg_1318 <= (col_1_phi_fu_361_p4 == smax3_reg_1280? 1'b1: 1'b0);
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
        icmp_reg_1303 <= (tmp_24_fu_450_p4 < ap_const_lv30_1? 1'b1: 1'b0);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        new_pix_B_V_reg_1385 <= {{inter_pix_data_V_dout[ap_const_lv32_17 : ap_const_lv32_10]}};
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        new_pix_G_V_reg_1378 <= {{inter_pix_data_V_dout[ap_const_lv32_F : ap_const_lv32_8]}};
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        new_pix_R_V_reg_1371 <= inter_pix_data_V_dout[7:0];
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == exitcond_fu_481_p2))) begin
        or_cond1_reg_1350 <= (tmp9_fu_533_p2 | tmp8_fu_528_p2);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == exitcond_fu_481_p2))) begin
        or_cond2_reg_1357 <= (tmp_11_reg_1308 & tmp_22_fu_544_p2);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == exitcond_fu_481_p2) & ~(ap_const_lv1_0 == or_cond2_fu_550_p2))) begin
        output_pixel_last_V_reg_1361 <= (col_assign_cast_fu_477_p1 == cols? 1'b1: 1'b0);
    end
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        row_1_reg_1293 <= (row_reg_346 + ap_const_lv31_1);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it2))) begin
        row_reg_346 <= row_1_reg_1293;
    end else if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        row_reg_346 <= ap_const_lv31_0;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it5))) begin
        sel_tmp_reg_1480 <= (sel_tmp22_demorgan_fu_1120_p2 ^ ap_const_lv1_1);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        if (tmp2_fu_402_p2) begin
            smax3_reg_1280 <= tmp_cast_fu_388_p1;
        end else begin
            smax3_reg_1280 <= ap_const_lv31_0;
        end

    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        if (tmp5_fu_416_p2) begin
            smax6_reg_1285 <= tmp1_cast_fu_398_p1;
        end else begin
            smax6_reg_1285 <= ap_const_lv31_0;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_15_reg_1327_pp0_it1))) begin
        temp_fu_156 <= buff_A_M_0_q0;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        tempx_B_V_fu_164 <= {{inter_pix_data_V_dout[ap_const_lv32_17 : ap_const_lv32_10]}};
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_17_reg_1346_pp0_it1))) begin
        tempx_G_V_fu_168 <= new_pix_G_V_reg_1378;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_17_reg_1346_pp0_it1))) begin
        tempx_R_V_fu_160 <= new_pix_R_V_reg_1371;
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it2))) begin
        tmp10_reg_1435 <= (y_weight_cast_cast_fu_847_p1 + tmp_2_0_2_i_cast7_cast_fu_851_p1);
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
        tmp_11_reg_1308 <= (row_reg_346 != ap_const_lv31_0? 1'b1: 1'b0);
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
        tmp_13_reg_1313 <= ($signed(tmp_s_reg_1270) < $signed(row_cast_fu_430_p1)? 1'b1: 1'b0);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == exitcond_fu_481_p2))) begin
        tmp_15_reg_1327 <= ($signed(col_assign_cast_fu_477_p1) < $signed(cols)? 1'b1: 1'b0);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == exitcond_fu_481_p2) & ~(ap_const_lv1_0 == tmp_15_fu_492_p2))) begin
        tmp_16_reg_1334[0] <= tmp_16_fu_497_p1[0];
        tmp_16_reg_1334[1] <= tmp_16_fu_497_p1[1];
        tmp_16_reg_1334[2] <= tmp_16_fu_497_p1[2];
        tmp_16_reg_1334[3] <= tmp_16_fu_497_p1[3];
        tmp_16_reg_1334[4] <= tmp_16_fu_497_p1[4];
        tmp_16_reg_1334[5] <= tmp_16_fu_497_p1[5];
        tmp_16_reg_1334[6] <= tmp_16_fu_497_p1[6];
        tmp_16_reg_1334[7] <= tmp_16_fu_497_p1[7];
        tmp_16_reg_1334[8] <= tmp_16_fu_497_p1[8];
        tmp_16_reg_1334[9] <= tmp_16_fu_497_p1[9];
        tmp_16_reg_1334[10] <= tmp_16_fu_497_p1[10];
        tmp_16_reg_1334[11] <= tmp_16_fu_497_p1[11];
        tmp_16_reg_1334[12] <= tmp_16_fu_497_p1[12];
        tmp_16_reg_1334[13] <= tmp_16_fu_497_p1[13];
        tmp_16_reg_1334[14] <= tmp_16_fu_497_p1[14];
        tmp_16_reg_1334[15] <= tmp_16_fu_497_p1[15];
        tmp_16_reg_1334[16] <= tmp_16_fu_497_p1[16];
        tmp_16_reg_1334[17] <= tmp_16_fu_497_p1[17];
        tmp_16_reg_1334[18] <= tmp_16_fu_497_p1[18];
        tmp_16_reg_1334[19] <= tmp_16_fu_497_p1[19];
        tmp_16_reg_1334[20] <= tmp_16_fu_497_p1[20];
        tmp_16_reg_1334[21] <= tmp_16_fu_497_p1[21];
        tmp_16_reg_1334[22] <= tmp_16_fu_497_p1[22];
        tmp_16_reg_1334[23] <= tmp_16_fu_497_p1[23];
        tmp_16_reg_1334[24] <= tmp_16_fu_497_p1[24];
        tmp_16_reg_1334[25] <= tmp_16_fu_497_p1[25];
        tmp_16_reg_1334[26] <= tmp_16_fu_497_p1[26];
        tmp_16_reg_1334[27] <= tmp_16_fu_497_p1[27];
        tmp_16_reg_1334[28] <= tmp_16_fu_497_p1[28];
        tmp_16_reg_1334[29] <= tmp_16_fu_497_p1[29];
        tmp_16_reg_1334[30] <= tmp_16_fu_497_p1[30];
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == exitcond_fu_481_p2))) begin
        tmp_17_reg_1346 <= (tmp_15_fu_492_p2 & tmp_8_reg_1298);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_17_reg_1346_pp0_it2))) begin
        tmp_26_reg_1415 <= {{tmp_5_i_fu_714_p2[ap_const_lv32_F : ap_const_lv32_8]}};
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_15_reg_1327_pp0_it2))) begin
        tmp_27_reg_1420 <= {{tmp_5_i1_fu_813_p2[ap_const_lv32_F : ap_const_lv32_8]}};
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_15_reg_1327_pp0_it1))) begin
        tmp_3_i1_reg_1400 <= (tmp_2_i1_fu_629_p2 + ap_const_lv13_80);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_17_reg_1346_pp0_it1))) begin
        tmp_3_i_reg_1390 <= (tmp_2_i_fu_597_p2 + ap_const_lv13_80);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_7_reg_1275 <= (cols + ap_const_lv32_FFFFFFFF);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it5))) begin
        tmp_8_i_reg_1470 <= (tmp_i2_fu_1104_p2 < ap_const_lv8_37? 1'b1: 1'b0);
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
        tmp_8_reg_1298 <= ($signed(row_cast_fu_430_p1) < $signed(rows)? 1'b1: 1'b0);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it5))) begin
        tmp_i2_reg_1465 <= (abs9_i_reg_1460 + abs_i_reg_1455);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it5))) begin
        tmp_i_s_reg_1475 <= (tmp_i2_fu_1104_p2 > ap_const_lv8_9B? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_s_reg_1270 <= (rows + ap_const_lv32_FFFFFFFF);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it3))) begin
        x_weight_3_reg_1445 <= (x_weight_2_fu_980_p2 - tmp_2_2_0_i_cast_fu_986_p1);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it2))) begin
        x_weight_reg_1430 <= (tmp_2_0_2_i_cast_fu_855_p1 - y_weight_cast8_fu_843_p1);
    end
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it3))) begin
        y_weight_2_reg_1450 <= (y_weight_1_fu_996_p2 - p_shl12_i_cast_fu_1012_p1);
    end
end

/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it6 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7 or exitcond3_fu_434_p2)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_logic_1 == ap_start) & ~(ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
        ap_NS_fsm = ap_ST_st0_fsm_0;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
        ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) | ((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)) | ((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
        ap_NS_fsm = ap_ST_st2_fsm_2;
    end else if ((((ap_ST_st0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_start)) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_start) & ~(ap_const_lv1_0 == exitcond3_fu_434_p2)))) begin
        ap_NS_fsm = ap_ST_st1_fsm_1;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm or exitcond3_fu_434_p2)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond3_fu_434_p2))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st0_fsm_0 == ap_CS_fsm)) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// buff_A_M_0_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond_reg_1318 or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7 or tmp_15_reg_1327)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_15_reg_1327))) begin
        buff_A_M_0_ce0 = ap_const_logic_1;
    end else begin
        buff_A_M_0_ce0 = ap_const_logic_0;
    end
end

/// buff_A_M_0_ce1 assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond_reg_1318_pp0_it3 or ap_reg_ppstg_tmp_17_reg_1346_pp0_it3)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_17_reg_1346_pp0_it3))) begin
        buff_A_M_0_ce1 = ap_const_logic_1;
    end else begin
        buff_A_M_0_ce1 = ap_const_logic_0;
    end
end

/// buff_A_M_0_we1 assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond_reg_1318_pp0_it3 or ap_reg_ppstg_tmp_17_reg_1346_pp0_it3)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_17_reg_1346_pp0_it3))) begin
        buff_A_M_0_we1 = ap_const_logic_1;
    end else begin
        buff_A_M_0_we1 = ap_const_logic_0;
    end
end

/// buff_A_M_1_ce0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7 or exitcond_fu_481_p2 or tmp_15_fu_492_p2)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == exitcond_fu_481_p2) & ~(ap_const_lv1_0 == tmp_15_fu_492_p2))) begin
        buff_A_M_1_ce0 = ap_const_logic_1;
    end else begin
        buff_A_M_1_ce0 = ap_const_logic_0;
    end
end

/// buff_A_M_1_ce1 assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond_reg_1318_pp0_it1 or ap_reg_ppstg_tmp_15_reg_1327_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_15_reg_1327_pp0_it1))) begin
        buff_A_M_1_ce1 = ap_const_logic_1;
    end else begin
        buff_A_M_1_ce1 = ap_const_logic_0;
    end
end

/// buff_A_M_1_we1 assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond_reg_1318_pp0_it1 or ap_reg_ppstg_tmp_15_reg_1327_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_15_reg_1327_pp0_it1))) begin
        buff_A_M_1_we1 = ap_const_logic_1;
    end else begin
        buff_A_M_1_we1 = ap_const_logic_0;
    end
end

/// buff_A_M_2_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond_reg_1318 or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7 or tmp_15_reg_1327)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_15_reg_1327))) begin
        buff_A_M_2_ce0 = ap_const_logic_1;
    end else begin
        buff_A_M_2_ce0 = ap_const_logic_0;
    end
end

/// buff_A_M_2_ce1 assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond_reg_1318_pp0_it1 or ap_reg_ppstg_tmp_15_reg_1327_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_15_reg_1327_pp0_it1))) begin
        buff_A_M_2_ce1 = ap_const_logic_1;
    end else begin
        buff_A_M_2_ce1 = ap_const_logic_0;
    end
end

/// buff_A_M_2_we0 assign process. ///
always @ (ap_CS_fsm or exitcond_reg_1318 or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7 or tmp_15_reg_1327)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_15_reg_1327))) begin
        buff_A_M_2_we0 = ap_const_logic_1;
    end else begin
        buff_A_M_2_we0 = ap_const_logic_0;
    end
end

/// col_1_phi_fu_361_p4 assign process. ///
always @ (ap_CS_fsm or col_1_reg_357 or exitcond_reg_1318 or ap_reg_ppiten_pp0_it1 or col_reg_1322)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        col_1_phi_fu_361_p4 = col_reg_1322;
    end else begin
        col_1_phi_fu_361_p4 = col_1_reg_357;
    end
end

/// inter_pix_data_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_1318 or tmp_17_reg_1346 or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        inter_pix_data_V_read = ap_const_logic_1;
    end else begin
        inter_pix_data_V_read = ap_const_logic_0;
    end
end

/// inter_pix_last_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_1318 or tmp_17_reg_1346 or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        inter_pix_last_V_read = ap_const_logic_1;
    end else begin
        inter_pix_last_V_read = ap_const_logic_0;
    end
end

/// inter_pix_strb_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_1318 or tmp_17_reg_1346 or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        inter_pix_strb_V_read = ap_const_logic_1;
    end else begin
        inter_pix_strb_V_read = ap_const_logic_0;
    end
end

/// inter_pix_tdest_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_1318 or tmp_17_reg_1346 or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        inter_pix_tdest_V_read = ap_const_logic_1;
    end else begin
        inter_pix_tdest_V_read = ap_const_logic_0;
    end
end

/// inter_pix_user_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_1318 or tmp_17_reg_1346 or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        inter_pix_user_V_read = ap_const_logic_1;
    end else begin
        inter_pix_user_V_read = ap_const_logic_0;
    end
end

/// out_pix_data_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_1318_pp0_it6 or ap_reg_ppstg_or_cond2_reg_1357_pp0_it6 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it6) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1357_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        out_pix_data_V_write = ap_const_logic_1;
    end else begin
        out_pix_data_V_write = ap_const_logic_0;
    end
end

/// out_pix_last_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_1318_pp0_it6 or ap_reg_ppstg_or_cond2_reg_1357_pp0_it6 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it6) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1357_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        out_pix_last_V_write = ap_const_logic_1;
    end else begin
        out_pix_last_V_write = ap_const_logic_0;
    end
end

/// out_pix_strb_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_1318_pp0_it6 or ap_reg_ppstg_or_cond2_reg_1357_pp0_it6 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it6) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1357_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        out_pix_strb_V_write = ap_const_logic_1;
    end else begin
        out_pix_strb_V_write = ap_const_logic_0;
    end
end

/// out_pix_tdest_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_1318_pp0_it6 or ap_reg_ppstg_or_cond2_reg_1357_pp0_it6 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it6) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1357_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        out_pix_tdest_V_write = ap_const_logic_1;
    end else begin
        out_pix_tdest_V_write = ap_const_logic_0;
    end
end

/// out_pix_user_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_85 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_1318_pp0_it6 or ap_reg_ppstg_or_cond2_reg_1357_pp0_it6 or ap_sig_bdd_120 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it6) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1357_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_85 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_120 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        out_pix_user_V_write = ap_const_logic_1;
    end else begin
        out_pix_user_V_write = ap_const_logic_0;
    end
end

/// ap_sig_bdd_120 assign process. ///
always @ (out_pix_data_V_full_n or out_pix_strb_V_full_n or out_pix_user_V_full_n or out_pix_last_V_full_n or out_pix_tdest_V_full_n or ap_reg_ppstg_exitcond_reg_1318_pp0_it6 or ap_reg_ppstg_or_cond2_reg_1357_pp0_it6)
begin
    ap_sig_bdd_120 = (((out_pix_data_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it6) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1357_pp0_it6)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it6) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1357_pp0_it6) & (out_pix_strb_V_full_n == ap_const_logic_0)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it6) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1357_pp0_it6) & (out_pix_user_V_full_n == ap_const_logic_0)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it6) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1357_pp0_it6) & (out_pix_last_V_full_n == ap_const_logic_0)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1318_pp0_it6) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1357_pp0_it6) & (out_pix_tdest_V_full_n == ap_const_logic_0)));
end

/// ap_sig_bdd_85 assign process. ///
always @ (inter_pix_data_V_empty_n or inter_pix_strb_V_empty_n or inter_pix_user_V_empty_n or inter_pix_last_V_empty_n or inter_pix_tdest_V_empty_n or exitcond_reg_1318 or tmp_17_reg_1346)
begin
    ap_sig_bdd_85 = (((inter_pix_data_V_empty_n == ap_const_logic_0) & (exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346)) | ((exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (inter_pix_strb_V_empty_n == ap_const_logic_0)) | ((exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (inter_pix_user_V_empty_n == ap_const_logic_0)) | ((exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (inter_pix_last_V_empty_n == ap_const_logic_0)) | ((exitcond_reg_1318 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_17_reg_1346) & (inter_pix_tdest_V_empty_n == ap_const_logic_0)));
end
assign buff_A_M_0_address0 = tmp_16_reg_1334;
assign buff_A_M_0_address1 = tmp_18_fu_886_p1;
assign buff_A_M_0_d1 = (tmp_26_reg_1415 + ap_const_lv8_10);
assign buff_A_M_1_addr_reg_13400 = $unsigned(col_1_phi_fu_361_p4);
assign buff_A_M_1_address0 = tmp_16_fu_497_p1;
assign buff_A_M_1_address1 = ap_reg_ppstg_buff_A_M_1_addr_reg_1340_pp0_it1;
assign buff_A_M_1_d1 = buff_A_M_0_q0;
assign buff_A_M_2_address0 = tmp_16_reg_1334;
assign buff_A_M_2_address1 = tmp_19_fu_620_p1;
assign buff_A_M_2_d0 = buff_A_M_1_q0;
assign buff_C_M_0_2_4_fu_836_p3 = ((ap_reg_ppstg_tmp_15_reg_1327_pp0_it2)? buff_A_M_2_q1: buff_C_M_0_2_fu_180);
assign col_assign_cast_fu_477_p1 = $unsigned(col_1_phi_fu_361_p4);
assign edge_B_V_fu_1165_p1 = $signed(sel_tmp4_fu_1150_p2);
assign edge_B_V_fu_1165_p3 = ((tmp_23_fu_1159_p2)? edge_B_V_fu_1165_p1: edge_val_fu_1131_p2);
assign edge_val_fu_1131_p2 = (tmp_i2_reg_1465 ^ ap_const_lv8_FF);
assign exitcond3_fu_434_p2 = (row_reg_346 == smax6_reg_1285? 1'b1: 1'b0);
assign exitcond_fu_481_p2 = (col_1_phi_fu_361_p4 == smax3_reg_1280? 1'b1: 1'b0);
assign icmp7_fu_517_p2 = (tmp_28_fu_507_p4 < ap_const_lv30_1? 1'b1: 1'b0);
assign neg7_i_cast_fu_1082_p2 = (ap_const_lv8_0 - y_weight_5_cast_fu_1056_p1);
assign neg_i_cast_fu_1060_p2 = (ap_const_lv8_0 - x_weight_4_cast_fu_1047_p1);
assign or_cond2_fu_550_p2 = (tmp_11_reg_1308 & tmp_22_fu_544_p2);
assign out_pix_data_V_din = p_Result_1_fu_1185_p3[23:0];
assign out_pix_last_V_din = ap_reg_ppstg_output_pixel_last_V_reg_1361_pp0_it6;
assign out_pix_strb_V_din = ap_const_lv3_7;
assign out_pix_tdest_V_din = ap_const_lv1_1;
assign out_pix_user_V_din = ap_const_lv1_1;
assign p_Repl2_1_fu_1181_p1 = $unsigned(p_Result_s_fu_1173_p3);
assign p_Result_1_fu_1185_p3 = {{p_Repl2_1_fu_1181_p1}, {edge_B_V_fu_1165_p3}};
assign p_Result_s_fu_1173_p3 = {{edge_B_V_fu_1165_p3}, {edge_B_V_fu_1165_p3}};
assign p_shl12_i_cast_fu_1012_p1 = $unsigned(p_shl12_i_fu_1006_p2);
assign p_shl12_i_fu_1006_p2 = tmp_2_2_1_i_cast_fu_1002_p1 << ap_const_lv9_1;
assign p_shl1_i1_cast_fu_766_p1 = $unsigned(p_shl1_i1_fu_760_p2);
assign p_shl1_i1_fu_760_p2 = retval_i_i1_cast1_fu_742_p1 << ap_const_lv9_1;
assign p_shl1_i_cast_fu_669_p1 = $unsigned(p_shl1_i_fu_663_p2);
assign p_shl1_i_fu_663_p2 = retval_i_i_cast1_fu_647_p1 << ap_const_lv9_1;
assign p_shl2_i1_cast_fu_794_p1 = $unsigned(p_shl2_i1_fu_788_p2);
assign p_shl2_i1_fu_788_p2 = retval_i7_i1_cast_fu_784_p1 << ap_const_lv15_7;
assign p_shl2_i_cast_fu_695_p1 = $unsigned(p_shl2_i_fu_689_p2);
assign p_shl2_i_fu_689_p2 = retval_i7_i_cast_fu_686_p1 << ap_const_lv15_7;
assign p_shl_i1_cast_fu_756_p1 = $unsigned(p_shl_i1_fu_750_p2);
assign p_shl_i1_fu_750_p2 = retval_i_i1_cast_fu_746_p1 << ap_const_lv14_6;
assign p_shl_i2_cast_fu_957_p1 = $unsigned(p_shl_i2_fu_951_p2);
assign p_shl_i2_fu_951_p2 = tmp_2_1_0_i_cast_fu_947_p1 << ap_const_lv9_1;
assign p_shl_i_cast_fu_659_p1 = $unsigned(p_shl_i_fu_653_p2);
assign p_shl_i_fu_653_p2 = retval_i_i_cast_fu_650_p1 << ap_const_lv14_6;
assign retval_i7_i1_cast9_cast_fu_780_p1 = $unsigned(tempx_G_V_fu_168);
assign retval_i7_i1_cast_fu_784_p1 = $unsigned(tempx_G_V_fu_168);
assign retval_i7_i_cast1_cast_fu_683_p1 = $unsigned(ap_reg_ppstg_new_pix_G_V_reg_1378_pp0_it2);
assign retval_i7_i_cast_fu_686_p1 = $unsigned(ap_reg_ppstg_new_pix_G_V_reg_1378_pp0_it2);
assign retval_i_i1_cast1_fu_742_p1 = $unsigned(tempx_R_V_fu_160);
assign retval_i_i1_cast_fu_746_p1 = $unsigned(tempx_R_V_fu_160);
assign retval_i_i_cast1_fu_647_p1 = $unsigned(ap_reg_ppstg_new_pix_R_V_reg_1371_pp0_it2);
assign retval_i_i_cast_fu_650_p1 = $unsigned(ap_reg_ppstg_new_pix_R_V_reg_1371_pp0_it2);
assign row_cast_fu_430_p1 = $unsigned(row_reg_346);
assign sel_tmp1_fu_1136_p2 = (tmp_i_s_reg_1475 & sel_tmp_reg_1480);
assign sel_tmp22_demorgan_fu_1120_p2 = (ap_reg_ppstg_or_cond1_reg_1350_pp0_it5 | tmp_8_i_fu_1108_p2);
assign sel_tmp3_fu_1145_p2 = (ap_reg_ppstg_or_cond1_reg_1350_pp0_it6 ^ ap_const_lv1_1);
assign sel_tmp4_fu_1150_p2 = (tmp_8_i_reg_1470 & sel_tmp3_fu_1145_p2);
assign tmp10_cast_fu_934_p1 = $unsigned(tmp10_reg_1435);
assign tmp1_cast_fu_398_p1 = tmp1_fu_392_p2[30:0];
assign tmp1_fu_392_p2 = (rows + ap_const_lv32_1);
assign tmp2_fu_402_p2 = ($signed(tmp_fu_382_p2) > $signed(32'b00000000000000000000000000000000)? 1'b1: 1'b0);
assign tmp3_fu_699_p2 = (p_shl2_i_cast_fu_695_p1 + tmp_i_cast_fu_679_p1);
assign tmp4_cast_fu_710_p1 = $unsigned(tmp4_fu_705_p2);
assign tmp4_fu_705_p2 = (tmp_3_i_reg_1390 + retval_i7_i_cast1_cast_fu_683_p1);
assign tmp5_fu_416_p2 = ($signed(tmp1_fu_392_p2) > $signed(32'b00000000000000000000000000000000)? 1'b1: 1'b0);
assign tmp6_fu_798_p2 = (p_shl2_i1_cast_fu_794_p1 + tmp_i1_cast_fu_776_p1);
assign tmp7_cast_fu_809_p1 = $unsigned(tmp7_fu_804_p2);
assign tmp7_fu_804_p2 = (tmp_3_i1_reg_1400 + retval_i7_i1_cast9_cast_fu_780_p1);
assign tmp8_fu_528_p2 = (icmp7_fu_517_p2 | tmp_13_reg_1313);
assign tmp9_fu_533_p2 = (icmp_reg_1303 | tmp_20_fu_523_p2);
assign tmp_15_fu_492_p2 = ($signed(col_assign_cast_fu_477_p1) < $signed(cols)? 1'b1: 1'b0);
assign tmp_16_fu_497_p1 = $unsigned(col_1_phi_fu_361_p4);
assign tmp_18_fu_886_p1 = $unsigned(ap_reg_ppstg_col_1_reg_357_pp0_it3);
assign tmp_19_fu_620_p1 = $unsigned(ap_reg_ppstg_col_1_reg_357_pp0_it1);
assign tmp_20_fu_523_p2 = ($signed(tmp_7_reg_1275) < $signed(col_assign_cast_fu_477_p1)? 1'b1: 1'b0);
assign tmp_21_fu_1140_p2 = (sel_tmp1_fu_1136_p2 | ap_reg_ppstg_or_cond1_reg_1350_pp0_it6);
assign tmp_22_fu_544_p2 = (col_1_phi_fu_361_p4 != ap_const_lv31_0? 1'b1: 1'b0);
assign tmp_23_fu_1159_p2 = (sel_tmp4_fu_1150_p2 | tmp_21_fu_1140_p2);
assign tmp_24_fu_450_p4 = {{row_reg_346[ap_const_lv32_1E : ap_const_lv32_1]}};
assign tmp_28_fu_507_p4 = {{col_1_phi_fu_361_p4[ap_const_lv32_1E : ap_const_lv32_1]}};
assign tmp_29_fu_1066_p3 = x_weight_4_fu_1042_p2[ap_const_lv32_A];
assign tmp_2_0_1_i_cast_fu_918_p1 = $unsigned(buff_C_M_0_1_2_reg_1405);
assign tmp_2_0_2_i_cast7_cast_fu_851_p1 = $unsigned(buff_C_M_0_2_4_fu_836_p3);
assign tmp_2_0_2_i_cast_fu_855_p1 = $unsigned(buff_C_M_0_2_4_fu_836_p3);
assign tmp_2_1_0_i_cast_fu_947_p1 = $unsigned(buff_C_M_1_1_fu_188);
assign tmp_2_1_2_i_cast_fu_967_p1 = $unsigned(buff_C_M_1_2_3_reg_1425);
assign tmp_2_2_0_i_cast_fu_986_p1 = $unsigned(buff_C_M_2_1_fu_184);
assign tmp_2_2_1_i_cast_fu_1002_p1 = $unsigned(buff_C_M_2_2_fu_172);
assign tmp_2_2_2_i_cast_fu_1039_p1 = $unsigned(buff_C_M_2_2_3_reg_1440);
assign tmp_2_i1_fu_629_p0 = tmp_2_i1_fu_629_p00;
assign tmp_2_i1_fu_629_p00 = $unsigned(tempx_B_V_fu_164);
assign tmp_2_i1_fu_629_p2 = ($signed({{1'b0}, {tmp_2_i1_fu_629_p0}}) * $signed('h19));
assign tmp_2_i_fu_597_p0 = tmp_2_i_fu_597_p00;
assign tmp_2_i_fu_597_p00 = $unsigned(new_pix_B_V_reg_1385);
assign tmp_2_i_fu_597_p2 = ($signed({{1'b0}, {tmp_2_i_fu_597_p0}}) * $signed('h19));
assign tmp_30_fu_1088_p3 = y_weight_3_fu_1051_p2[ap_const_lv32_A];
assign tmp_4_1_2_i_cast_fu_976_p1 = $unsigned(tmp_4_1_2_i_fu_970_p2);
assign tmp_4_1_2_i_fu_970_p2 = tmp_2_1_2_i_cast_fu_967_p1 << ap_const_lv9_1;
assign tmp_5_i1_fu_813_p2 = (tmp7_cast_fu_809_p1 + tmp6_fu_798_p2);
assign tmp_5_i_fu_714_p2 = (tmp4_cast_fu_710_p1 + tmp3_fu_699_p2);
assign tmp_6_0_1_i_cast_fu_927_p1 = $unsigned(tmp_6_0_1_i_fu_921_p2);
assign tmp_6_0_1_i_fu_921_p2 = tmp_2_0_1_i_cast_fu_918_p1 << ap_const_lv9_1;
assign tmp_8_i_fu_1108_p2 = (tmp_i2_fu_1104_p2 < ap_const_lv8_37? 1'b1: 1'b0);
assign tmp_cast_fu_388_p1 = tmp_fu_382_p2[30:0];
assign tmp_fu_382_p2 = (cols + ap_const_lv32_1);
assign tmp_i1_cast_fu_776_p1 = $unsigned(tmp_i1_fu_770_p2);
assign tmp_i1_fu_770_p2 = (p_shl_i1_cast_fu_756_p1 + p_shl1_i1_cast_fu_766_p1);
assign tmp_i2_fu_1104_p2 = (abs9_i_reg_1460 + abs_i_reg_1455);
assign tmp_i_cast_fu_679_p1 = $unsigned(tmp_i_fu_673_p2);
assign tmp_i_fu_673_p2 = (p_shl_i_cast_fu_659_p1 + p_shl1_i_cast_fu_669_p1);
assign x_weight_1_fu_961_p0 = $signed(x_weight_reg_1430);
assign x_weight_1_fu_961_p2 = (x_weight_1_fu_961_p0 - p_shl_i2_cast_fu_957_p1);
assign x_weight_2_fu_980_p2 = (x_weight_1_fu_961_p2 + tmp_4_1_2_i_cast_fu_976_p1);
assign x_weight_4_cast_fu_1047_p1 = x_weight_4_fu_1042_p2[7:0];
assign x_weight_4_fu_1042_p2 = (x_weight_3_reg_1445 + tmp_2_2_2_i_cast_fu_1039_p1);
assign y_2_fu_906_p2 = (tmp_27_reg_1420 + ap_const_lv8_10);
assign y_weight_1_fu_996_p2 = (y_weight_2_cast_fu_943_p1 - tmp_2_2_0_i_cast_fu_986_p1);
assign y_weight_2_cast_fu_943_p1 = $unsigned(y_weight_fu_937_p2);
assign y_weight_3_fu_1051_p2 = (y_weight_2_reg_1450 - tmp_2_2_2_i_cast_fu_1039_p1);
assign y_weight_5_cast_fu_1056_p1 = y_weight_3_fu_1051_p2[7:0];
assign y_weight_cast8_fu_843_p1 = $unsigned(buff_C_M_0_1_fu_176);
assign y_weight_cast_cast_fu_847_p1 = $unsigned(buff_C_M_0_1_fu_176);
assign y_weight_fu_937_p2 = (tmp10_cast_fu_934_p1 + tmp_6_0_1_i_cast_fu_927_p1);
always @ (posedge ap_clk)
begin
    tmp_16_reg_1334[63:31] <= 33'b000000000000000000000000000000000;
end



endmodule //sobel_filter

